### ISSUE TITLE
Unable to login or register outside of localhost

### ISSUE THREAD

**Issue by Jack423** [Bikranshu/express-react-boilerplate#28]
I set 0.0.0.0 to the host IP and checked the firewall settings. The login page loads, but you are unable to log in or register when the sign-in button or register button is clicked.

**Comment by Bikranshu** [comment]
Can you share a screenshot of error?

**Comment by Jack423** [comment]
There actually isn't any error. You are just unable to sign into the site outside of localhost. I made a quick video showing what is happening and I show the console in both my laptop (connected to the internet on the same network) and my desktop (also on the same network but hosting the webserver).

https://photos.app.goo.gl/UNf9eFYydt4NtZc79

**Comment by Bikranshu** [comment]
> There actually isn't any error. You are just unable to sign into the site outside of localhost. I made a quick video showing what is happening and I show the console in both my laptop (connected to the internet on the same network) and my desktop (also on the same network but hosting the webserver).
> 
> https://photos.app.goo.gl/UNf9eFYydt4NtZc79

Please try again.
